language: android
jdk: oraclejdk8
env:
  global:
  - secure: "UgMJGt86OncekW54gy1ZixXz1I2TnMXNBoOqBU9hFMklErNYDlrl5hBCqAZXGI+oRDZGkAVHIUMqDKaSK2WsImRbQtZS+X+W8sjmfAw0s13HO8CKQEtzdpYZw09vgmKGj9BDajJafvmXT6P77twducrbM7q6gH3qAiZxub3+pYzor19ef8QUBLsuoVrv1LWw4nKE4LxDa9Lkt05lkr3YSO0BVkOIU+eZmwVvyv2uxFY7D1TRKRnXMvCFwlmHGmgWNDaCMs4rfjuvBOp626ONmv2cZQN46i9iqKJa4MP8uD6/dv8C95JpunFBVTmOwP3Jdu2S94eOT5AXOVUf51/YYWfNIv9tvLIlN2LV5vhbgumutP/rSM5RA6RRb89c9mJTGlDxcXX6kNcsLHIJp9hcmOgRH6oElXOGcTJ5eAz6QxD/XTiVUA6QeU6rXJIxBIbSEHh8L8eYcrwLElVHVvqAecsVCKCmPUrwx2CYfFvxpUGZ7Wfb7C4V4huWzrF5a5IZuoRALKysiShuO1RITyXRHaYqi6qfTUYI8ozCECJ2qVPALB7G27UiMxu1NA97wxWQcc++MQv2CILysFBYONAgSF4A9oivINR0t/bplVL1VLI4FFpu4beKfMz7hlJxs1O6kr6U+MoXCoS5VYvAhvV1Km6BP+LGcJlQsqD0i9H7zC8="
  - secure: "MiDovslCuylKOxYkLj/nmkIC5pyZT5K0LYRDH6OKCe7P7Qb+opf+tCfIXccOSrezGXti8deSCGZpqXnFdDI/DNWXBrqSbXmVxqtA3OS+HqYn7KhjF//kKpNiJbjjMIWrjsYiNEFhDmKQvN8dYsPFi6IRDxtiQVuwETLAr+wMs5g1n0eCmXa45/+Sm84nDFlBozavW7+44TZ1UwNvDb9MQWx0ZvRTp1ZodEL4iusbZOuZEXThH1JKLeFGB09ps7sNbrWYq7pH6v0leJdLbzGJXt4ZMZ/3kEZJGzSgvupK/n3NXyqP0fvAlEUSXdW2JtHSSDGcZxhVZvYYG/4zytnae6snsSq94I8BsETaxFtmROdIpr5fVyrkye3CD952wPFIrfUmJ8pxCInzIYUt537KUBhgQUVc21JcbTScA/A98ELfSDueHl3N8HBusGzGGRKCfsf5EQAlIwyxE4t5fs+lcZVvkEcVnUZegRhY+/FDfU70pqNaQLuMnL2eogqkPmezf5tg4f5jkqwulZ4DiZ8wFM5X9am3uOd091RgIUIX9PwKRLrCsy6A0LXk3neApQvNidVhJvM1uR1wq/Ba1yj2+NHy53N7tjNd174OYn+X6meLhUzDeyIASnyKCbem4V/6isvfvj4iavlm2u9Eb7+3dJT0DIcIErH4rdFNZvPGm84="
android:
  components:
  - tools
  - platform-tools
  - android-28
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  chmod +x gradlew
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_script:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
script: ./gradlew test build
deploy:
  provider: script
  script: ./gradlew clean && ./gradlew build && ./gradlew install && ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true