name: Bintray deploy # TODO migrate to Maven Central

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20 # Fetch 20 last commits, should be enough for changelogs
      - name: Fetch Git tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew clean
      - name: Assemble
        run: ./gradlew assemble
      - name: Install
        run: ./gradlew install
      - name: Upload
        run: ./gradlew bintrayUpload
        env:
          bintrayUsername: ${{ secrets.BINTRAY_NAME }}
          bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
      - name: Prepare Slack notification message
        id: prepare_slack_message
        run: |
          wget https://raw.githubusercontent.com/AckeeCZ/android-github-actions-scripts/master/slack/prepare_slack_msg.sh
          chmod u+x prepare_slack_msg.sh
          ./prepare_slack_msg.sh
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ job.status == 'success' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.ANDROID_OSS_NOTIFICATION_WEBHOOK }}
          SLACK_USERNAME: 'github-snitch'
          SLACK_ICON_EMOJI: ':octocat:'
          SLACK_TITLE: ${{ steps.prepare_slack_message.outputs.SLACK_MSG_TITLE }}
          SLACK_MESSAGE: ${{ steps.prepare_slack_message.outputs.SLACK_MSG }}
          MSG_MINIMAL: true
