name: Android build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20 # Fetch 20 last commits, should be enough for changelogs
      - name: Fetch Git tags
        run: |
          git fetch --prune --unshallow --tags
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew clean
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew test
